version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pos_db_container
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # optional: expose MySQL on host (not necessary if only used internally)

  web:
    build: .
    container_name: pos_web_container
    restart: always
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"  # map container port 5000 to host port 5000
    depends_on:
      - db

volumes:
  db_data:
